#ifndef GUARD_CONSTANTS_SPEAKER_NAMES_H
#define GUARD_CONSTANTS_SPEAKER_NAMES_H

enum SpeakerNames {
    SP_NAME_NONE = 0,
    SP_NAME_PLAYER,
    SP_NAME_RIVAL,
    SP_NAME_MAGMA,
    SP_NAME_AQUA,
    SP_NAME_DIGLETT,
    SP_NAME_AGENT_DIGGS,
    SP_NAME_COURTNEY,
    SP_NAME_SHELLY,
    SP_NAME_PLAYER_AQUA,
    SP_NAME_PLAYER_MAGMA,
    SP_NAME_EXEGGUTOR,
    SP_NAME_TOXAPEX,
    SP_NAME_CORSOLA,
    SP_NAME_VOLCANION,
    SP_NAME_PIKACHU,
    SP_NAME_CRAMORANT,
    SP_NAME_GRAPPLOCT,
    SP_NAME_COUNT
};

enum SpeakerColorIds {
    SP_COLOR_NORMAL = 0,
    SP_COLOR_MAGMA,
    SP_COLOR_AQUA,
    SP_COLOR_COUNT
};

#endif // GUARD_CONSTANTS_SPEAKER_NAMES_H
