gText_Birch_Welcome::
	.string "Hey, you!\p"
	.string "Next GRUNT in line, get over here!\p"
	.string "{FONT 5}(Sigh…)\p"
	.string "{FONT_NORMAL}Alright, so I've given this whole\n"
	.string "lecture way too many times today,\l"
	.string "so you get the TLDR.\p"
	.string "You're here at CAVE NAME to scout it\n"
	.string "out before the main team {FONT 5}(me) {FONT_NORMAL}does\l"
	.string "a proper investigation.\p"
	.string "We've had reports of an unknown\n"
	.string "WATER-type Legendary POKéMON\l"
	.string "causing a ruckus at the deepest\l"
	.string "part of the cave.\p"
	.string "Whatever you do, DO NOT approach it\n"
	.string "if you happen to run into it.\p"
	.string "That's for us ADMINS to handle.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "We've had some problems with GRUNTS\n"
	.string "bringing their POOCHYENA to our\l"
	.string "EXTREMELY IMPORTANT missions.\p"
	.string "That STUPID KID keeps interfering\n"
	.string "with our plans because those GRUNTS\l"
	.string "aren't bringing enough WATER-types\l"
	.string "{FONT 5}(the best type) {FONT_NORMAL}with them.\p"

	@ add the carvanha retreat here
	.string "{FONT_NORMAL}Oh yeah. We have a new… {FONT 5}ugh… {FONT_NORMAL}\p"
	.string "{MIN_LETTER_SPACING 2}P{PAUSE 3} R{PAUSE 3} O{PAUSE 3} T{PAUSE 3} O{PAUSE 3} C{PAUSE 3} O{PAUSE 3} L{PAUSE 3} .\p"
	.string "{MIN_LETTER_SPACING 0}{FONT 5}{AUTO_SCROLL 1}ok so i know that archie is under a LOT of\n"
	.string "stress right now with everything that\l"
	.string "happened last week but would it KILL him\l"
	.string "to not push a bunch of new orders on me\l"
	.string "while i'm trying to clean up HIS MESS??\l"
	.string "he acts like he owns the whole team!!!\l"
	.string "i mean i guess he technically does but i was\l"
	.string "supposed to get my VACATION this week and\l"
	.string "suddenly that's out the window because\l"
	.string "THERES TOO MUCH DAMN WATER IN DEWFORD!!!!!{PAUSE 40}\p"
	.string "{FONT_NORMAL}.{PAUSE 50}\n"
	.string ".{PAUSE 50}\l"
	.string "{AUTO_SCROLL 0}uh…\p"
	.string "Sorry you had to hear all that.\p"
	.string "All the damage control work for last\n"
	.string "week's incident with KYOGRE has been\l"
	.string "catastrophic for my sleep schedule.\p"
	.string "As I was TRYING to say, its now AQUA\n"
	.string "policy that you have to sign a waiver\l"
	.string "before any hazardous missions.\p"
	.string "\n"
	.string "$"

gText_Birch_AndYouAre::
	.string "Just let me know your name and gender\n"
	.string "and you'll be good to go.\p$"

gText_Birch_BoyOrGirl::
	.string "Gender first, please.$"

gText_Birch_WhatsYourName::
	.string "Perfect.\n"
	.string "And your name?$"

gText_Birch_SoItsPlayer::
	.string "Just to make sure I have that right,\n"
	.string "it's {PLAYER}{KUN}?\p$"

gText_Birch_YourePlayer::
	.string "Great, thanks.\n"
	.string "You're all set to go now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Hey, {PLAYER}{KUN}!\p"
	.string "This is our last chance to show HOENN\n"
	.string "what we as TEAM AQUA can do!\p"
	.string "{AUTO_SCROLL 1}Go make the BOSS proud!!{PAUSE 40}\n"
	.string "{AUTO_SCROLL 0}{FONT 5}(and y'know… make my job easier for me…)\p"

	@ hey boss just so you know ive tested none of this from here on, sorry about that but it is past my bedtime

	@ fade out, fade courtney in
	.string "{FONT_NORMAL}Next GRUNT please.\p"
	.string "Sorry for the wait. The loudmouth at\n"
	.string "the TEAM AQUA check-in made me want\l"
	.string "to hit her with a rock.\p"
	.string "Violent urges have been surpressed.\n"
	.string "For now.\p"
	.string "You heard what she said, right?\p"
	.string "As much as I loathe to say it, most of\n"
	.string "the details in her speech were correct.\p"
	.string "The only amendment I can make is the\n"
	.string "reports of the Legendary POKéMON in\l"
	.string "the depths of CAVE NAME prove without\l"
	.string "a doubt that it is a FIRE-type.\p"
	.string "$"	

	@ enter numel, stage middle
	.string "Here is your partner for the mission.\p"
	.string "I can think of no POKéMON more suited\n"
	.string "to this mission than NUMEL.\p"
	.string "In addition to being the most adorable\n"
	.string "POKéMON, NUMEL can help you climb up\l"
	.string "rocky walls to reach areas that are\l."
	.string "normally inaccesible on foot.\p"
	.string "To be quite honest, I wish I was also\n"
	.string "provided a NUMEL today.\p"
	.string "I have been looking for a sixth NUMEL\n"
	.string "to join my party, but I have been too\l"
	.string "busy with my work lately to dedicate\l"
	.string "the time to catching another.\p"
	.string "Such is the life of a TEAM MAGMA ADMIN."
	.string "$"

	@ back into the ball with numel
	.string "I have taken too much of your time.\n"
	.string "I apologize.\p"
	.string "Let us fill out your paperwork."
	.string "$"

	@ gText_Birch_AndYouAre equivalent for magma player
	.string "I will need your name and gender.\p$"

	@ gText_Birch_BoyOrGirl equavilent for magmo pleyar
	.string "Your gender, please?$"

	@ gText_Birch_WhatsYourName you get the idea
	.string "Your name?$"

	@ gText_Birch_SoItsPlayer yeah yeah yeah (hey! hey! hey! hey!) (cool rhythm heaven ds reference for you there)
	.string "{PLAYER}{KUN} is correct?\p$"

	@ gText_Birch_YourePlayer theres too many of these
	.string "Thank you, {PLAYER}{KUN}.\p$"

	@ fade magma player in
	.string "You and NUMEL will find the Legendary\n"
	.string "POKéMON below and capture it.\p"
	.string "Do not fail your mission.\p"
	.string "That said, we will not tolerate\n"
	.string "reckless behaviour.\p"
	.string "If you find yourself in a bind,\n"
	.string "find someone nearby to help you.\p"
	.string "Take advantage of the TEAM AQUA\n"
	.string "GRUNTS if you must.\p"
	.string "We cannot afford to lose any more of\n"
	.string "our GRUNTS today.\p"
	.string "I wish you the best of luck."
	.string "$"

	@ shrink magma player, go to gameplay


